# Generated by Django 5.2.3 on 2025-07-04 14:01

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("entityid", models.CharField(unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["entityid"], name="entities_su_entityi_0bfba0_idx")
                ],
            },
        ),
    ]
