"""
This type stub file was generated by pyright.
"""

from django_redis.client.default import DefaultClient

_main_exceptions = ...

class Marker:
    """
    Dummy class for use as
    marker for herded keys.
    """

    ...

class HerdClient(DefaultClient):
    def __init__(self, *args, **kwargs) -> None: ...
    def set(self, key, value, timeout=..., version=..., client=..., nx=..., xx=...):  # -> bool:
        ...
    def get(self, key, default=..., version=..., client=...):  # -> Any | None:
        ...
    def get_many(self, keys, version=..., client=...):  # -> dict[Any, Any] | OrderedDict[Any, Any]:
        ...
    def set_many(self, data, timeout=..., version=..., client=..., herd=...):  # -> None:
        """
        Set a bunch of values in the cache at once from a dict of key/value
        pairs. This is much more efficient than calling set() multiple times.

        If timeout is given, that timeout will be used for the key; otherwise
        the default cache timeout will be used.
        """
        ...

    def incr(self, *args, **kwargs): ...
    def decr(self, *args, **kwargs): ...
    def touch(self, key, timeout=..., version=..., client=...):  # -> bool:
        ...
