"""
This type stub file was generated by pyright.
"""

from django_redis.client.default import DefaultClient

def replace_query(url, query): # -> str:
    ...

class SentinelClient(DefaultClient):
    """
    Sentinel client which uses the single redis URL specified by the CACHE's
    LOCATION to create a LOCATION configuration for two connection pools; One
    pool for the primaries and another pool for the replicas, and upon
    connecting ensures the connection pool factory is configured correctly.
    """
    def __init__(self, server, params, backend) -> None:
        ...
    
    def connect(self, *args, **kwargs): # -> Redis:
        ...
    


