"""
This type stub file was generated by pyright.
"""

VERSION = ...
__version__ = ...
from redis import Redis

def get_redis_connection(alias=..., write=...) -> Redis:
    """
    Helper used for obtaining a raw redis client.
    """
    ...
