"""
This type stub file was generated by pyright.
"""

from redis import Redis

VERSION = ...
__version__ = ...

def get_redis_connection(alias=..., write=...) -> Redis:
    """
    Helper used for obtaining a raw redis client.
    """
    ...
