"""
This type stub file was generated by pyright.
"""

class ConnectionInterrupted(Exception):
    def __init__(self, connection, parent=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class CompressorError(Exception):
    ...


