"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Iterator
from typing import Optional

class HashRing:
    nodes: list[str] = ...
    def __init__(self, nodes: Iterable[str] = ..., replicas: int = ...) -> None:
        ...
    
    def add_node(self, node: str) -> None:
        ...
    
    def remove_node(self, node: str) -> None:
        ...
    
    def get_node(self, key: str) -> Optional[str]:
        ...
    
    def get_node_pos(self, key: str) -> tuple[Optional[str], Optional[int]]:
        ...
    
    def iter_nodes(self, key: str) -> Iterator[tuple[Optional[str], Optional[str]]]:
        ...
    
    def __call__(self, key: str) -> Optional[str]:
        ...
    


