# Generated by Django 5.2.3 on 2025-07-04 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trustmarks", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trustmark",
            unique_together={("tmt", "domain")},
        ),
    ]
