name: Build and run tests

permissions: {}
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          components: rustfmt, clippy
          toolchain: stable

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0

      - name: actions-setup-redis
        uses: shogo82148/actions-setup-redis@v1.42.0
        with:
          auto-start: false
          distribution: "valkey"
          redis-version: "7.2"

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Build TA appliation
        run: cargo build

      - name: Run tests for inmor
        run: just test
